### ISSUE TITLE
DataLossError

### ISSUE THREAD

**Issue by datquocnguyen** [FrankWork/conv_relation#5]
Hi, thanks for releasing the source code.
I got an *DataLossError* error when running the code. The log files show that your code was running fine. So I do not know what happened when running your code on my computer.
Do you have any idea for what happened ? 
Thank you very much.
Best,
Dat.

2018-01-12 16:43:37.268221: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: truncated record at 5986508
Traceback (most recent call last):
  File "src/train.py", line 170, in <module>
    tf.app.run()
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/train.py", line 164, in main
    train(sess, m_train, m_valid)
  File "src/train.py", line 103, in train
    _, loss, acc = sess.run(fetches)
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 5986508
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,6], [?], [?,?], [?,?], [?,?]], output_types=[DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

Caused by op u'IteratorGetNext', defined at:
  File "src/train.py", line 170, in <module>
    tf.app.run()
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/train.py", line 139, in main
    train_data, test_data, word_embed = base_reader.inputs()
  File "/Users/dqnguyen/workspace/RelationExtraction/conv_relation-master/src/reader/base.py", line 317, in inputs
    pad_value, shuffle=True)
  File "/Users/dqnguyen/workspace/RelationExtraction/conv_relation-master/src/reader/base.py", line 280, in read_tfrecord_to_batch
    batch = iterator.get_next()
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 259, in get_next
    name=name))
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 706, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Users/dqnguyen/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): truncated record at 5986508
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,6], [?], [?,?], [?,?], [?,?]], output_types=[DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

**Comment by FrankWork** [comment]
When did this error occur? Could you remove the generated TFRecord files, `rm data/*.tfrecord`, and run again?

**Comment by datquocnguyen** [comment]
Thanks for your suggestion. It's running now.
Best,
Dat.

**Comment by xdesky** [comment]
Hello Dat,
I'm install complete. But App not support All Vietnamese language. 
input: 
`xin chào bạn tên tôi là Nguyễn Văn Đạt`
output: 
```
1	ï»¿xin	N	_	_		_
2	chÃ o	Np	_	_		_
3	báº¡n	V	_	_		_
4	tÃªn	Np	_	_		_
5	tÃ´i	Np	_	_		_
6	lÃ 	Np	_	_		_
7	Nguyá»	Np	_	_		_
8	…	CH	_	_		_
9	n	N	_	_		_
10	VÄƒn	Np	_	_		_
11	Ä?áº¡t	Np	_	_		_
```

Please, Help me!!!
Thanks!!

**Comment by FrankWork** [comment]
@xdesky did your problem related to my repository? My code does not  produce the output of this format.
